/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUI;

import java.util.ArrayList;
import java.util.function.Consumer;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author marl8n
 */
public class NewJFrame extends javax.swing.JFrame {
    
    class User {
        String nombre;
        String DPI;
        Double saldo;
        
        User (String nombre, String DPI, String saldo){
            this.nombre = nombre;
            this.DPI = DPI;
            this.saldo = Double.parseDouble(saldo);
        }
    }
    
    ArrayList<User> usuarios = new ArrayList<User>();
    
    int idx = -1;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        ButtonGroup radioGroup = new ButtonGroup();
        radioGroup.add(radioButtonDeposito);
        radioGroup.add(radioButtonRetiro);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldDPI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFIeldSaldo = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldBusqueda = new javax.swing.JTextField();
        buttonSarch = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();
        labelDPI = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        radioButtonDeposito = new javax.swing.JRadioButton();
        radioButtonRetiro = new javax.swing.JRadioButton();
        textFieldMoney = new javax.swing.JTextField();
        buttonDoOperation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("DPI");

        jLabel3.setText("Saldo");

        addButton.setText("Agregar");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Agregar Persona");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Retiros/Depositos");

        jLabel6.setText("Buscar por DPI");

        buttonSarch.setText("Buscar");
        buttonSarch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSarchMouseClicked(evt);
            }
        });

        labelName.setText("Nombre: ");

        labelDPI.setText("DPI: ");

        labelSaldo.setText("Saldo: ");

        radioButtonDeposito.setLabel("Deposito");

        radioButtonRetiro.setLabel("Retiro");

        buttonDoOperation.setText("Hacer Operación");
        buttonDoOperation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDoOperationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFIeldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDPI, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSaldo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioButtonDeposito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioButtonRetiro)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(buttonDoOperation))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldBusqueda)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(buttonSarch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(textFIeldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonSarch)))
                .addGap(26, 26, 26)
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDPI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSaldo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonDeposito)
                    .addComponent(radioButtonRetiro)
                    .addComponent(textFieldMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDoOperation))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        this.usuarios.add(new User(
                this.textFieldNombre.getText(),
                this.textFieldDPI.getText(),
                this.textFIeldSaldo.getText()
        ));
        this.textFieldNombre.setText("");
        this.textFieldDPI.setText("");
        this.textFIeldSaldo.setText("");
    }//GEN-LAST:event_addButtonMouseClicked

    private void buttonSarchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSarchMouseClicked
        for ( int i = 0; i < this.usuarios.size(); i++ ){
            if (usuarios.get(i).DPI.toString().equals(this.textFieldBusqueda.getText())){
                this.labelName.setText("Nombre: " + this.usuarios.get(i).nombre);
                this.labelDPI.setText("DPI: " + this.usuarios.get(i).DPI);
                this.labelSaldo.setText("Saldo: " + this.usuarios.get(i).saldo.toString());
                idx = i;
            }
        }
    }//GEN-LAST:event_buttonSarchMouseClicked

    private void buttonDoOperationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDoOperationMouseClicked
        if(this.radioButtonDeposito.isSelected()){
            usuarios.get(idx).saldo += Double.parseDouble(textFieldMoney.getText());
            textFieldMoney.setText("");
            labelName.setText("Nombre: ");
            labelDPI.setText("DPI: ");
            labelSaldo.setText("Saldo: ");
            idx = -1;
            textFieldMoney.setText("");
            labelName.setText("Nombre: ");
            labelDPI.setText("DPI: ");
            labelSaldo.setText("Saldo: ");
            textFieldBusqueda.setText("");
        }
        else if(this.radioButtonRetiro.isSelected()){
            if(usuarios.get(idx).saldo < Double.parseDouble(textFieldMoney.getText() ) ){
                JOptionPane.showMessageDialog(rootPane, "No tiene fondos suficientes!");
            }
            else{
                usuarios.get(idx).saldo -= Double.parseDouble(textFieldMoney.getText());
                textFieldMoney.setText("");
                labelName.setText("Nombre: ");
                labelDPI.setText("DPI: ");
                labelSaldo.setText("Saldo: ");
                idx = -1;
                textFieldBusqueda.setText("");
            }
        }
    }//GEN-LAST:event_buttonDoOperationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton buttonDoOperation;
    private javax.swing.JButton buttonSarch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelDPI;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JRadioButton radioButtonDeposito;
    private javax.swing.JRadioButton radioButtonRetiro;
    private javax.swing.JTextField textFIeldSaldo;
    private javax.swing.JTextField textFieldBusqueda;
    private javax.swing.JTextField textFieldDPI;
    private javax.swing.JTextField textFieldMoney;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
